packages:
  - apps/*
  - packages/*
catalog:
  "@eslint/compat": ^1.3.1
  "@eslint/js": ^9.22.0
  "@sveltejs/adapter-auto": ^6.0.0
  "@sveltejs/kit": ^2.22.0
  "@sveltejs/package": ^2.0.0
  "@sveltejs/vite-plugin-svelte": ^6.0.0
  "@tailwindcss/vite": ^4.0.12
  "@types/node": ^22.13.8
  cookie: ^1.0.2
  eslint: ^9.29.0
  eslint-config-prettier: ^10.1.1
  eslint-import-resolver-typescript: ^4.4.3
  eslint-plugin-import-x: ^4.15.2
  eslint-plugin-jsdoc: ^51.3.3
  eslint-plugin-svelte: ^3.4.0
  globals: ^16.0.0
  jiti: ^2.4.2
  prettier: ^3.5.3
  prettier-plugin-svelte: ^3.3.3
  prettier-plugin-tailwindcss: ^0.6.11
  publint: ^0.3.2
  rimraf: ^6.0.1
  svelte: ^5.0.0
  svelte-check: ^4.0.0
  svelte-eslint-parser: ^1.1.1
  tailwind-variants: ^1.0.0
  tailwindcss: ^4.1.10
  tsx: ^4.19.3
  turbo: ^2.5.4
  typescript: ^5.8.2
  typescript-eslint: ^8.35.0
  vite: ^7.0.4
